#!/bin/sh

# get the project path
project_path=$1
# store the tox path
tox_path=`pwd`

# create tox project
mkdir $project_path
touch $project_path/index.html
cat src/index.html > $project_path/index.html

# files
cd $project_path
mkdir src
touch src/main.js
cat $tox_path/src/main.js > src/main.js
mkdir src/assets src/components src/views
touch src/components/hello.mjs
cat $tox_path/src/hello.mjs > src/components/hello.mjs
cat $tox_path/src/index.mjs > src/views/index.mjs
